# Generated by Django 4.2.20 on 2025-05-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_logout_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
