# Generated by Django 4.2.20 on 2025-04-04 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('principal_name', models.CharField(blank=True, max_length=100)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('college_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('autonomous', 'Autonomous')], default='private', max_length=20)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('accreditation', models.CharField(blank=True, max_length=100)),
                ('hostel_availability', models.BooleanField(default=False)),
                ('hostel_capacity_boys', models.PositiveIntegerField(blank=True, null=True)),
                ('hostel_capacity_girls', models.PositiveIntegerField(blank=True, null=True)),
                ('library', models.BooleanField(default=False)),
                ('library_books_count', models.PositiveIntegerField(blank=True, null=True)),
                ('labs', models.TextField(blank=True)),
                ('placement_cell', models.BooleanField(default=False)),
                ('placement_percentage', models.FloatField(blank=True, null=True)),
                ('top_recruiters', models.TextField(blank=True)),
                ('other_facilities', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='college_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Profile',
                'verbose_name_plural': 'College Profiles',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='colleges.collegeprofile')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hod_name', models.CharField(blank=True, max_length=100)),
                ('faculty_count', models.PositiveIntegerField(default=0)),
                ('labs', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField()),
                ('fees_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='colleges.collegeprofile')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='colleges.degree')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('credits', models.PositiveIntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
