# Generated by Django 4.2.20 on 2025-04-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='cycle',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('degree', 'cycle', 'name')},
        ),
    ]
