# Generated by Django 4.2.20 on 2025-05-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.admissioncycle'),
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.degree'),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.seat'),
        ),
        migrations.AddField(
            model_name='application',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.section'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.collegeprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'section_name', 'cycle')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('degree', 'cycle', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('college', 'cycle', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='admissioncycle',
            unique_together={('college', 'year')},
        ),
    ]
