# Generated by Django 4.2.20 on 2025-04-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_remove_degree_cycle_alter_department_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='degree',
            name='cycle',
            field=models.ForeignKey(default=1, help_text='The cycle this degree is offered in', on_delete=django.db.models.deletion.CASCADE, to='colleges.admissioncycle'),
            preserve_default=False,
        ),
    ]
