# Generated by Django 4.2.20 on 2025-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_admissioncycle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='class_12_stream',
            field=models.CharField(max_length=50),
        ),
    ]
