# Generated by Django 4.2.20 on 2025-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_collegeprofile_district_alter_collegeprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeprofile',
            name='district',
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
