# Generated by Django 4.2.20 on 2025-04-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_alter_application_class_12_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='colleges.degree'),
        ),
    ]
