# Generated by Django 4.2.20 on 2025-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_remove_collegeprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
