# Generated by Django 4.2.20 on 2025-04-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_application_degree'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
