# Generated by Django 4.2.20 on 2025-04-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_alter_degree_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('degree', 'cycle', 'name')},
        ),
    ]
