# Generated by Django 4.2.20 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncycle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='admissioncycle',
            unique_together={('college', 'year')},
        ),
    ]
