# Generated by Django 4.2.20 on 2025-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('school', 'School'), ('college', 'College'), ('super_admin', 'Super Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
