# Generated by Django 4.2.20 on 2025-05-01 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=10)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.admissioncycle')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('principal_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('school_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Government Aided', 'Government Aided')], max_length=50)),
                ('board_affiliation', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board', 'State Board'), ('IB', 'IB'), ('Other', 'Other')], max_length=50)),
                ('medium_of_instruction', models.CharField(choices=[('English', 'English'), ('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Other', 'Other')], max_length=50)),
                ('established_year', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('total_teachers', models.IntegerField()),
                ('school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('affiliation_certificate', models.FileField(blank=True, null=True, upload_to='school_certificates/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='school_brochures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_filled', models.BooleanField(default=False)),
                ('seat_order', models.PositiveIntegerField(blank=True, help_text='Numeric part of seat_number for ordering', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='schools.classsection')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('author_role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('alumni', 'Alumni'), ('teacher', 'Teacher'), ('other', 'Other')], help_text='Role of the person giving the testimonial', max_length=50)),
                ('message', models.TextField(help_text='The testimonial message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('school_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('total_sections', models.PositiveIntegerField(default=1)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.admissioncycle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.schoolprofile')),
            ],
        ),
        migrations.AddField(
            model_name='classsection',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='schools.schoolprofile'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('admission_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be 12 digits.')])),
                ('student_contact_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be 10 digits.')])),
                ('permanent_address', models.TextField()),
                ('correspondence_address', models.TextField(blank=True)),
                ('caste', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('Other', 'Other')], max_length=20)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], max_length=20)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be 10 digits.')])),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be 10 digits.')])),
                ('previous_school_name', models.CharField(max_length=200)),
                ('previous_school_address', models.TextField()),
                ('board_of_education', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board', 'State Board'), ('Other', 'Other')], max_length=20)),
                ('class_last_attended', models.CharField(max_length=20)),
                ('year_of_passing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)])),
                ('percentage_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('birth_certificate', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('aadhaar_card', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('caste_certificate', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('previous_mark_sheet', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('transfer_certificate', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('passport_photo', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('address_proof', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='schools.admissioncycle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='schools.schoolprofile')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='schools.schoolclass')),
                ('seat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='schools.seat')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='schools.classsection')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='admissioncycle',
            unique_together={('school', 'year')},
        ),
    ]
