# Generated by Django 4.2.20 on 2025-03-21 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('total_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='school_profiles/')),
                ('school_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('international', 'International')], max_length=20, null=True)),
                ('medium_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('start_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('end_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('is_co_education', models.BooleanField(default=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('has_transport', models.BooleanField(default=False)),
                ('school_motto', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
