# Generated by Django 4.2.20 on 2025-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
