# Generated by Django 4.2.20 on 2025-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_classsection_filled_seats_admissioncycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncycle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
