# Generated by Django 4.2.20 on 2025-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_admission_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
