# Generated by Django 4.2.20 on 2025-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_admission_admission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20),
        ),
    ]
