# Generated by Django 4.2.20 on 2025-03-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='schools.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='schools.schoolprofile')),
            ],
        ),
    ]
