# Generated by Django 4.2.20 on 2025-03-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_remove_schoolgallery_school_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolRating',
        ),
    ]
