# Generated by Django 4.2.20 on 2025-03-27 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_delete_schoolrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('school_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='schools.schoolprofile')),
            ],
        ),
    ]
