# Generated by Django 4.2.20 on 2025-03-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolGallery',
        ),
    ]
