# Generated by Django 4.2.20 on 2025-03-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_schoolgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('author_role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('alumni', 'Alumni'), ('teacher', 'Teacher'), ('other', 'Other')], help_text='Role of the person giving the testimonial', max_length=50)),
                ('message', models.TextField(help_text='The testimonial message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='schools.schoolprofile')),
            ],
        ),
    ]
